name: "xqyh's blog"
description: "小群一号的官方博客"

avatar: https://raw.githubusercontent.com/cgy6666/cgy6666.github.io/refs/heads/main/images/fKhbGm7gZ.jpeg
favicon: https://raw.githubusercontent.com/cgy6666/cgy6666.github.io/refs/heads/main/images/fKhbGm7gZ.ico

navigation:
  - name: 首页
    url: /
  - name: 关于
    url: /about
  - name: 分类
    url: /tags

paginate: 8

excerpt_separator: <!-- more -->

footer-links:
  zhihu: wei-xin-yong-hu-16-68-4
  email: 2304342691@qq.com
  facebook:
  github: cgy6666
  rss: welcome!
  twitter: 
  youtube:

footer-text: Copyright (c) 2026 FIRESTAR

url: https://cgy6666.github.io

permalink: /:title/
paginate_path: /page:num/

# Gitalk
gitalk:
  clientID: Ov23liVPo6tZwZ0aylrq
  clientSecret: de2653582d4df67dd7e1d81f31d08da2749c70b2
  repo: cgy6666.github.io
  owner: cgy6666

# The release of Jekyll Now
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

